name: Auto Collect Nodes

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Script
        env:
          GIST_ID: ${{ secrets.MY_GIST_ID }}
          GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
        run: |
          # 自动寻找入口文件
          TARGET_FILE=$(find . -name "collect.py" -o -name "main.py" | head -n 1)
          
          if [ -z "$TARGET_FILE" ]; then
            echo "错误：仓库里没找到 python 脚本！"
            exit 1
          fi
          
          TARGET_DIR=$(dirname "$TARGET_FILE")
          FILENAME=$(basename "$TARGET_FILE")
          
          cd "$TARGET_DIR"
          [ -f "requirements.txt" ] && pip install -r requirements.txt
          
          # 运行程序
          python "$FILENAME" -g $GIST_ID -k $GH_TOKEN -t clash v2ray singbox
